FROM maven:3.6.3-jdk-13 AS build
COPY pom.xml /tmp/
RUN mvn -B dependency:go-offline -f /tmp/pom.xml -s /usr/share/maven/ref/settings-docker.xml
COPY src /tmp/src/
WORKDIR /tmp/
RUN mvn -B -s /usr/share/maven/ref/settings-docker.xml package

FROM openjdk:13-jdk-alpine
EXPOSE 8761

RUN mkdir /app
COPY --from=build /tmp/target/*.jar /app/app.jar
COPY src/main/resources/* ./

ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app/app.jar"]