version: '3.4'
services:
 mysqldb:
   image: mysql:8.0
   expose:
     - "3306"
   ports:
     - "3306:3306"
   restart: always
   volumes:
     - ./db_data:/var/lib/mysql:rw
   environment:
     MYSQL_USER: root
     MYSQL_PASSWORD: admin
     MYSQL_DATABASE: smarthouse
     MYSQL_ROOT_PASSWORD: admin

 discovery-server:
   restart: always
   expose:
     - "8761"
   ports:
     - "8761:8761"
   build:
     context: eurekalab
     dockerfile: Dockerfile

 apigateway:
   restart: always
   expose:
     - "8081"
   build:
     context: apigateway
     dockerfile: Dockerfile
   ports:
     - "8081:8081"

 authservice:
   restart: always
   ports:
    - "8085:8085"
   build:
     context: authservice
     dockerfile: Dockerfile

 searchservice:
   restart: always
   ports:
    - "8084:8084"
   build:
     context: searchservice
     dockerfile: Dockerfile

 profile-control:
   restart: always
   ports:
    - "8080:8080"
   build:
     context: profile-control
     dockerfile: Dockerfile

 sensorgen:
   restart: always
   ports:
    - "8082:8082"
   build:
     context: sensorgen
     dockerfile: Dockerfile

 websocket:
   restart: always
   ports:
    - "8086:8086"
   build:
     context: websocket
     dockerfile: Dockerfile

volumes:
  db_data: